### ISSUE TITLE
Try pyoxidizer as an alternative to PyInstaller

### ISSUE THREAD

**Issue by simonw** [simonw/datasette.app#21]
As a backup plan for if I can't get the PyInstaller one to start in less than 9 seconds (https://github.com/simonw/datasette.app/issues/17#issuecomment-908571782).

**Comment by simonw** [comment]
Following the getting started guide: https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_getting_started.html#getting-started

In a new virtual environment I ran:

    pip install pyoxidizer
    pyoxidizer init-config-file datasette
    cd datasette
    pyoxidizer run

I got this error:

> unable to find suitable Apple SDK supporting macosx11.1 or newer

https://developer.apple.com/forums/thread/667561 suggested manually adding symlinks to help it find them. I opted to reinstall the XCode command-line tools instead using the recipe from https://apple.stackexchange.com/a/375535

    sudo rm -rf /Library/Developer/CommandLineTools
    xcode-select --install

**Comment by simonw** [comment]
Having done that, `pyoxidizer run` worked as advertised: after churning away for a while it got to:
```
locating Apple SDK macosx11.1+ supporting macosx10.9
using SDK /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk (macosx11.1 targeting macosx10.9)
building with Rust 1.54.0
    Updating crates.io index
```
And then eventually:
```
   Compiling jemallocator v0.3.2
    Finished dev [unoptimized + debuginfo] target(s) in 1m 22s
installing files to /private/tmp/cxfreeze/datasette/./build/x86_64-apple-darwin/debug/install
Python 3.9.6 (default, Jul 24 2021, 22:44:27) 
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by simonw** [comment]
Next I tried adding the `python_config.run_command = "import uuid; print(uuid.uuid4())"` line to `pyoxidizer.bzl` as suggested in the getting started tutorial - after running `pyoxidizer run` I can now generate UUIDs like so:
```
% build/x86_64-apple-darwin/debug/install/datasette 
4b678628-76e4-4860-bec7-e6eb5b367294
% build/x86_64-apple-darwin/debug/install/datasette 
3e79af16-b856-462f-a8c8-f04f18e0ffd8
```
Startup time is _really_ fast:
```
% time build/x86_64-apple-darwin/debug/install/datasette 
82df0f90-944b-4163-845b-697515e0ea3a
build/x86_64-apple-darwin/debug/install/datasette  0.03s user 0.01s system 87% cpu 0.039 total
```

**Comment by simonw** [comment]
Continuing to follow the tutorial I got to the bit about `pyflakes`. I switched the example around to try and run `datasette` instead - my code (stripped of comments) now looked like this:
```
def make_exe():
    dist = default_python_distribution()
    policy = dist.make_python_packaging_policy()
    python_config = dist.make_python_interpreter_config()
    python_config.run_command = "from datasette.cli import cli; cli()"
    exe = dist.to_python_executable(
        name="datasette",
        packaging_policy=policy,
        config=python_config,
    )
    for resource in exe.pip_install(["datasette==0.59a2"]):
        resource.add_location = "in-memory"
        exe.add_python_resource(resource)
    return exe
```
I got this error:
```
Caused by:
    extension module markupsafe._speedups cannot be loaded from memory but memory loading required
   --> ./pyoxidizer.bzl:251:9
    |
251 |         exe.add_python_resource(resource)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ add_python_resource


error: adding PythonExtensionModule<name=markupsafe._speedups>

Caused by:
    extension module markupsafe._speedups cannot be loaded from memory but memory loading required
```

**Comment by simonw** [comment]
I tried skipping those compiled-to-C speedup modules (the `_yaml` one too):

```python
    for resource in exe.pip_install(["datasette==0.59a2"]):
        if resource.name not in ("markupsafe._speedups", "yaml._yaml"):
            resource.add_location = "in-memory"
            exe.add_python_resource(resource)
```

**Comment by simonw** [comment]
It almost worked but failed with this error:
```
installing files to /private/tmp/cxfreeze/datasette/./build/x86_64-apple-darwin/debug/install
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "datasette.cli", line 15, in <module>
  File "datasette.app", line 89, in <module>
NameError: name '__file__' is not defined
error: cargo run failed
```

**Comment by simonw** [comment]
https://github.com/simonw/datasette/blob/67cbf0ae7243431bf13702e6e3ba466b619c4d6f/datasette/app.py#L89 is this line:

```python
app_root = Path(__file__).parent.parent
```

**Comment by simonw** [comment]
The option in #22 is promising enough that I'm not going to put any more work into PyOxidizer just yet.

**Comment by avioli** [comment]
I was going to suggest to look at PyOxidizer and searched closed issue to see you have :)

I love the way you file issues for yourself and then "document" actions taken and outcomes of success and failures. I like it very much.
